apiVersion: v1
kind: Service
metadata:
  name: {{lower .Values.name}}-svc
  labels:
    app:  {{lower .Values.name}}-svc
spec:
  type:  {{lower .Values.serviceType}}
  selector:
    app: {{lower .Values.name}}
  ports:
  - name: grpc
    port: {{lower .Values.servicePort}}
    targetPort: {{lower .Values.serviceTargetPort}}
