apiVersion: v1
kind: Service
metadata:
  name: {{lower .Values.name}}-svc
  labels:
    app:  {{lower .Values.name}}
spec:
  type:  ClusterIP
  selector:
    app: {{lower .Values.name}}
  ports:
  - name: grpc
    port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{lower .Values.name}}-svc-external
  labels:
    app: {{lower .Values.name}}-svc-external
spec:
  type: LoadBalancer
  selector:
    app: {{lower .Values.name}}
  ports:
  - name: http
    port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
